---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Uma tabela de booleanos
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una tabela de números
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Uma tabela com as linhas que atendem à condição
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Uma coluna de booleanos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Uma coluna de números
  checked: false
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: arboles\[("altura"|'altura')\]\s*>=\s*3
name: Uma coluna verdadeira?
