---
locale: pt
tags: []
layout: input_bottom
editor: external
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: TODO
name: Eu te conheço
